### ISSUE TITLE
Issue while building from source

### ISSUE THREAD

**Issue by UtkarshVerma** [acrisci/playerctl#69]
I get the following error when I build from the source:
```sh
➜  playerctl git:(master) make
make  all-recursive
make[1]: Entering directory '/home/utkarsh/GitHub/playerctl'
Making all in playerctl
make[2]: Entering directory '/home/utkarsh/GitHub/playerctl/playerctl'
/usr/bin/gdbus-codegen --generate-c-code playerctl-generated mpris-dbus-interface.xml
make  all-am
make[3]: Entering directory '/home/utkarsh/GitHub/playerctl/playerctl'
  CC       playerctl-player.lo
  CC       playerctl-generated.lo
  CCLD     libplayerctl-1.0.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       playerctl-playerctl-cli.o
playerctl-cli.c: In function ‘handle_player_command’:
playerctl-cli.c:298:55: warning: too many arguments for format [-Wformat-extra-args]
   g_set_error(error, playerctl_cli_error_quark (), 1, "Command not recognized: %s", command[0], NULL);
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CCLD     playerctl
  GEN      playerctl-1.0.pc
make[3]: Leaving directory '/home/utkarsh/GitHub/playerctl/playerctl'
make[2]: Leaving directory '/home/utkarsh/GitHub/playerctl/playerctl'
Making all in doc
make[2]: Entering directory '/home/utkarsh/GitHub/playerctl/doc'
Making all in reference
make[3]: Entering directory '/home/utkarsh/GitHub/playerctl/doc/reference'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/utkarsh/GitHub/playerctl/doc/reference'
make[3]: Entering directory '/home/utkarsh/GitHub/playerctl/doc'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/utkarsh/GitHub/playerctl/doc'
make[2]: Leaving directory '/home/utkarsh/GitHub/playerctl/doc'
make[2]: Entering directory '/home/utkarsh/GitHub/playerctl'
make[2]: Leaving directory '/home/utkarsh/GitHub/playerctl'
make[1]: Leaving directory '/home/utkarsh/GitHub/playerctl'
```

**Comment by UtkarshVerma** [comment]
@acrisci It's an issue with the format specifiers. Please correct it.

**Comment by acrisci** [comment]
Can you try the build with meson? I've announced I'm going to remove the autotools build system soon and I don't feel like maintaining it anymore.

```
meson build
ninja -C build
```

**Comment by acrisci** [comment]
That warning should be fixed in cff5710.

**Comment by UtkarshVerma** [comment]
`make` still fails but I was able to build `playerctl` using `meson`

**Comment by UtkarshVerma** [comment]
I think you should update the README for building instructions.

**Comment by UtkarshVerma** [comment]
#Fixed
